### ISSUE TITLE
RAM not available

### ISSUE THREAD

**Issue by drewr** [elastic/runbld#11]
On OpenSUSE 13.2, we had a problem finding the total RAM. `memorysize_mb` is populated in facter, so we should have grabbed that.

```
>>>>>>>>>>>> SCRIPT EXECUTION BEGIN >>>>>>>>>>>>
Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:type :runbld.system/error, :msg "can't get memory info from:\nnil\n"} {:type :runbld.system/error, :msg "can't get memory info from:\nnil\n"}
        at runbld.system$find_ram_mb.invoke(system.clj:47)
        at runbld.system$memory_details.invoke(system.clj:53)
        at runbld.system$fn__4755$inspect_system__4756$fn__4757.invoke(system.clj:99)
        at runbld.system$fn__4755$inspect_system__4756.invoke(system.clj:74)
        at runbld.system$fn__4773$wrap_system__4774$fn__4775$fn__4776.invoke(system.clj:106)
        at runbld.main$_main.doInvoke(main.clj:56)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at runbld.main.main(Unknown Source)
Build step 'Execute shell' marked build as failure
```

**Comment by drewr** [comment]
`$HOME` is not set.

```
>>>>>>>>>>>> SCRIPT EXECUTION BEGIN >>>>>>>>>>>>
Exception in thread "main" java.lang.AssertionError: Assert failed: ("facter" "--yaml"): Error: couldn't find HOME environment -- expanding `~'

(= 0 (:exit res))
	at runbld.util.io$run.doInvoke(io.clj:9)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at runbld.system$facter.invoke(system.clj:22)
	at runbld.system$fn__4759$inspect_system__4760$fn__4761.invoke(system.clj:79)
	at runbld.system$fn__4759$inspect_system__4760.invoke(system.clj:77)
	at runbld.system$fn__4777$wrap_system__4778$fn__4779$fn__4780.invoke(system.clj:109)
	at runbld.main$_main.doInvoke(main.clj:56)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at runbld.main.main(Unknown Source)
```

**Comment by drewr** [comment]
Not sure what to make of:

```
slave-e3f06c27:~> env - HOME=/var/lib/jenkins facter
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='hardwaremodel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
Could not retrieve fact='kernel', resolution='<anonymous>': undefined method `split' for nil:NilClass
undefined method `split' for nil:NilClass
```

**Comment by drewr** [comment]
Solution we've come up with is standardizing on facter `3.1.3` across systems. Will try and make it backward-compat.

**Comment by drewr** [comment]
Also just found out about `--show-legacy`. Will probably use that as a bridge.
