### ISSUE TITLE
Java discovery doesn't work on Windows

### ISSUE THREAD

**Issue by drewr** [elastic/runbld#33]
```
java -jar "C:\Program Files\runbld\src\runbld-0.99.41\runbld" C:\Windows\TEMP\hudson7852076919719173061.sh 
Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:type :runbld.io/missing-file, :msg "can't find C:\\Program Files\\Java\\jdk1.8.0_92\\bin\\java.exe", :path "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Amazon\\cfn-bootstrap\\;C:\\ProgramData\\Chocolatey\\bin;C:\\Program Files\\Puppet Labs\\Puppet\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Java\\jdk1.8.0_92\\bin;C:\\Program Files (x86)\\vim\\vim74;C:\\Program Files\\infra\\bin"} {:type :runbld.io/missing-file, :msg "can't find C:\\Program Files\\Java\\jdk1.8.0_92\\bin\\java.exe", :path "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Amazon\\cfn-bootstrap\\;C:\\ProgramData\\Chocolatey\\bin;C:\\Program Files\\Puppet Labs\\Puppet\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Java\\jdk1.8.0_92\\bin;C:\\Program Files (x86)\\vim\\vim74;C:\\Program Files\\infra\\bin"}
	at runbld.io$which.invokeStatic(io.clj:93)
	at runbld.io$which.invoke(io.clj:89)
	at runbld.io$fn__1888$resolve_binary__1893$fn__1894.invoke(io.clj:109)
	at runbld.io$fn__1888$resolve_binary__1893.invoke(io.clj:107)
```

**Comment by drewr** [comment]
This seems to be related to the fact that `where.exe` will return *all* the `%PATH%`-resolvable matches.

```
C:\Users\vagrant>where.exe java
C:\ProgramData\Oracle\Java\javapath\java.exe
C:\Program Files\Java\jdk1.8.0_92\bin\java.exe

C:\Users\vagrant>
```

Which looks like:

```
runbld.io> (which "java")
"C:\\ProgramData\\Oracle\\Java\\javapath\\java.exe\r\nC:\\Program Files\\Java\\jdk1.8.0_92\\bin\\java.exe"
```

Will split on newline and grab the first, which will still work on `which(1)`.

**Comment by drewr** [comment]
OK, so that's a problem, but I can't make it reproduce the original error.  This one makes sense given the behavior of `where.exe`:

```
1. Unhandled java.nio.file.InvalidPathException
   Illegal char <> at index 44:
   C:\ProgramData\Oracle\Java\javapath\java.exe C:\Program
   Files\Java\jdk1.8.0_92\bin\java.exe
```

**Comment by drewr** [comment]
Tracked it down. The real error is:

```
{:exit 2,
 :out "",
 :err "ERROR: Invalid pattern is specified in \"path:pattern\".\r\n"}
```

Which matches `cmd.exe`:

```
C:\Users\vagrant>where.exe C:\ProgramData\Oracle\Java\javapath\java.exe
ERROR: Invalid pattern is specified in "path:pattern".
```

The problem is that we call `resolve-binary` multiple times in `runbld.java`, which works fine with `which(1)` but not `where.exe`.
