### ISSUE TITLE
runbld fails when scm clone is true but wipe-workspace is false

### ISSUE THREAD

**Issue by leathekd** [elastic/runbld#78]
Basically, it cannot clone when the workspace already exists and is populated.  It should probably run `git pull` instead.

<details>

```
[elastic+elasticsearch+5.4+packaging-tests] $ /usr/local/bin/runbld --last-good-commit elastic+elasticsearch+5.4+multijob-intake /tmp/jenkins846470968449712863.sh
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
runbld>>> runbld started
runbld>>> 1.3.7/cd451cb20de4e95b3a5b26f6f2bf7812b27d466d
runbld>>> BUILD: https://5086a1f436ee16623a447bdf25881bbc.us-east-1.aws.found.io:9243/build-1463180427010/t/20170606193430-2367880D
runbld>>> cloning git@github.com:elastic/elasticsearch.git
Exception in thread "main" java.lang.AssertionError: Assert failed: ["clone" ("git@github.com:elastic/elasticsearch.git" "<https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+packaging-tests/ws/"> "--reference" "/var/lib/jenkins/.git-references/elasticsearch.git" "--branch" "5.3")]:
out:
err: fatal: destination path '<https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+packaging-tests/ws/'> already exists and is not an empty directory.

(= 0 (:exit r))
	at clj_git.core$run$err__2817.invoke(core.clj:36)
	at clj_git.core$run.invokeStatic(core.clj:43)
	at clj_git.core$run.invoke(core.clj:29)
	at clj_git.core$run.invokeStatic(core.clj:31)
	at clj_git.core$run.invoke(core.clj:29)
	at clj_git.core$git_clone.invokeStatic(core.clj:225)
	at clj_git.core$git_clone.invoke(core.clj:208)
	at runbld.main$fn__11744$bootstrap_workspace__11749$fn__11750.invoke(main.clj:84)
	at runbld.main$fn__11744$bootstrap_workspace__11749.invoke(main.clj:63)
	at runbld.main$fn__11908$fn__11909.invoke(main.clj:138)
	at runbld.main$fn__11899$fn__11900.invoke(main.clj:137)
	at runbld.main$fn__11890$fn__11891.invoke(main.clj:136)
	at runbld.main$fn__11881$fn__11882.invoke(main.clj:135)
	at runbld.main$fn__11872$fn__11873.invoke(main.clj:134)
	at runbld.main$fn__11863$fn__11864.invoke(main.clj:133)
	at runbld.main$_main.invokeStatic(main.clj:160)
	at runbld.main$_main.doInvoke(main.clj:150)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at runbld.main.main(Unknown Source)
Build step 'Execute shell' marked build as failure
```

</details>

**Comment by leathekd** [comment]
I suppose ```pull``` might be insufficient as the branch could have changed (or could be new).  Perhaps ```fetch```, ```checkout```, and finally ```pull``` would be more correct...

**Comment by drewr** [comment]
I almost never find `pull` to be correct in automation. It's a shortcut when developing. Usually a `fetch` and a `checkout -f origin/foo` is better for a computer.

**Comment by leathekd** [comment]
Thanks for the tip.  I just found that clj-git.core/git-checkout actually does a `-f` so I'll remove the `pull` and see how it goes.
